### ISSUE TITLE
ContoursReport publishing incorrect NetworkTable keys

### ISSUE THREAD

**Issue by tom131313** [WPIRoboticsProjects/GRIP#432]
ContoursReport publishing user selected values "area" and "height" creates NetworkTables keys "height" and "centerY" (and once I saw "solidity" and "height".

Fields are passed "positionally" and have different names in the User Interface and the NetworkTables.  I didn't check for any other instances of this type of error.

Portion of .grip file deployed to the roboRIO:
```xml
   < grip:Step name="Publish ContoursReport">
   < /grip:Input>
      < grip:Input step="3" socket="5">
        < value>true</value>
      < /grip:Input>
      < grip:Input step="3" socket="6">
        < value>true</value>
```

**Comment by ThomasJClark** [comment]
Can you post  a screenshot of your pipeline and outlineviewer?

**Comment by tom131313** [comment]
I'm sorry for the delay for providing more information.

Most of our team's PCs are 32 bit and include a small ClassMate (and all
team PCs are Windows 7).  I was happy GRIP ran on the ClassMate.  When
you distributed GRIP v1.1.1 temporarily without 32 bit support I was able
to borrow our 64 bit machine to continue evaluation of GRIP but now the
64 bit machine is being used elsewhere.

When I'm able to get the 64 bit machine again, I'll respond.  Or maybe
you will distribute the 32 bit version before I am able to use the 64 bit
machine.  Thanks.

**Comment by tom131313** [comment]
Steps to test error:

Notice Contour Report has "height" and "area."
![grip-gui](https://cloud.githubusercontent.com/assets/16885334/12665844/c72051de-c608-11e5-8be5-22ef166bb97f.PNG)

Deploy the GRIP project on the driver station PC to the roboRIO.

(Using PuTTY to the roboRIO I see a java process is started on the roboRIO.)

Stop the GRIP driver Station deploy and close the deploy window.  (Doesn't seem to matter when the deploy is stopped, actually.)

Deploy my C++ robot program that uses GRIP on the roboRIO from Eclipse.
(A new java process is created.)

Open the Network Table Viewer in Eclipse on the driver station PC (client mode).

![networktables](https://cloud.githubusercontent.com/assets/16885334/12665862/eafb8808-c608-11e5-931c-23bd1010c7f5.PNG)

Notice that "MyTargetTable" has "height" and "solidity" even though the GRIP project has "height" and "area."

__CURIOUSLY!!!:__
If I click on the driver station PC GRIP window (gets focus) and then click on the Network Table Viewer window (gets focus), then the "area" does appear in place of "solidity" for about 1/2 second in the Network Table Viewer and then returns to "solidity."  The "area" appears briefly despite the GRIP deploy not running (stopped and closed the deploy window).  Closing the GRIP program on the driver station PC doesn't change the Network Table Viewer - still shows "height" and "solidity."

**Comment by cartycrabber** [comment]
Confirming this report, it seems that the check boxes are linked to different values than they display. Unchecking "Publish Solidity" results in center x not being published while solidity is. Unchecking "Publish Center X" results in width not being published while center x is, and so on.

**Comment by JLLeitschuh** [comment]
@ThomasJClark Can you look into this one. This sounds like a blocking issue.

**Comment by ThomasJClark** [comment]
The publish operations get the list of fields you can publish using Java reflection.  This is super helpful for maintaining the code, since we can can just have a "Publish *x*" step for any given *x* without writing a bunch of boilerplate code.  Unfortunately, it turns out that the order that Java gives us the list of fields is actually undefined behavior, so it can return them in different orders on different JVM versions.

What's happening here is that your desktop Java install gives `area` and `height` as the 4th and 5th fields of `ContourReport`, so you've checked the 4th and 5th checkboxes.  However, the roboRIO's JVM returns the fields in such an order that `height` and `solidity` are the 4th and 5th ones, so it publishes those.

The best solution is likely to make it so the `ContoursReport` class (and other similar classes) can explicitly define an index for each publishable field. I'll begin work on that.
