### ISSUE TITLE
URLDecoder.decode(String) is deprecated

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsProjects/GRIP#594]
ui/src/main/java/edu/wpi/grip/ui/DeployController.java uses URLDecoder.decode(String) -- a deprecated API.  Should be updated to the explicit API.

[URLDecoder (Java Platform SE 8)](https://docs.oracle.com/javase/8/docs/api/java/net/URLDecoder.html)

**Comment by JLLeitschuh** [comment]
Yea, I saw that. Didn't know how to fix it.
If you want to take a crack at it go ahead.

**Comment by ZeusChops** [comment]
There is now a URLDecoder.decode(String, String). Usage: URLDecoder.decode(String, "UTF-8") would work as a replacement for the current URLDecoder.decode(String).

Note: URLDecoder.decode(String, String) throws an UnsupportedEncodingException if the wrong value is put in for the second string - instead of "UTF-8" you put "UTF8" or something else - i.e. "NTFS".
