### ISSUE TITLE
Generated Python getting outputs is ugly

### ISSUE THREAD

**Issue by PeterMitrano** [WPIRoboticsProjects/GRIP#751]
Getting the outputs of generated python requires doing something like `pipeline.last_cv_output_name`. If you change your pipeline, then the output variable name changes, and you have to change your code. There should be a nicer way to get the output. One simple hack would be to put `self.output = self.last_cv_output_name` at the end of the process function. Or, you could simply return the last output from the process method. Either way, it would be nice to not have to rename code when I move around my pipeline

**Comment by SamCarlberg** [comment]
This is intentional and applies to all languages, not just Python.

If the generated pipeline changes that much, then the parts of the program that use it will also have to change. There's no getting around it. Also, the last step in the pipeline might not be the only step that the user wants to get outputs from.
